import{i as y,S as P,a as C}from"./assets/vendor-BDaiwwc1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const f=e=>{const r=document.querySelector(".gallery");if(!Array.isArray(e)||e.length===0){y.error({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topCenter"});return}e.forEach(({webformatURL:s,largeImageURL:t,tags:n,likes:a,views:S,comments:q,downloads:v})=>{const l=document.createElement("div");l.classList.add("gallery-item"),l.innerHTML=`
      <a href="${t}" class="gallery-link">
        <img src="${s}" alt="${n}" class="gallery-image"/>
        <div class="info">
          <p><b>Likes:</b> ${a}</p>
          <p><b>Views:</b> ${S}</p>
          <p><b>Comments:</b> ${q}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </a>
    `,r.appendChild(l)}),new P(".gallery a").refresh()},p=()=>{const e=document.querySelector(".loader");e?e.style.display="block":console.error("Loading indicator not found.")},b=()=>{const e=document.querySelector(".loader");e?setTimeout(()=>{e.style.display="none"},500):console.error("Loading indicator not found.")},E=()=>{const e=document.querySelector("#load-more-btn");e.style.display="block"},d=()=>{const e=document.querySelector("#load-more-btn");e.style.display="none",y.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"})},$="47394574-2a816324e728e13b0469414a4",I="https://pixabay.com/api/";let g=1;const u=()=>g,L=e=>{g=e},w=async e=>{const r=`${I}?key=${$}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${g}&per_page=15`;try{return p(),(await C.get(r)).data}catch(o){throw console.error(o),o}finally{b()}},M=document.querySelector("#search-form"),m=document.querySelector("#search-input"),A=document.querySelector("#load-more-btn");let c="",h=!0;const i=e=>{y.error({title:"Error",message:e,position:"topCenter"})},B=()=>{const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy(0,e*2)};M.addEventListener("submit",async e=>{if(e.preventDefault(),c=m.value.trim(),c===""){i("Please enter a search term.");return}h||L(1),p();const r=document.querySelector(".gallery");r.innerHTML="";try{const o=await w(c),s=o.hits,t=o.totalHits;s.length===0?i("There are no images matching your search query. Please try again!"):(f(s),t>u()*15?E():d())}catch{i("An error occurred while fetching images.")}finally{b()}h=!1,m.value=""});A.addEventListener("click",async()=>{const e=u();if(e>=15){d();return}L(e+1);try{const r=await w(c),o=r.hits,s=r.totalHits;o.length===0?i("No more images available."):(f(o),u()*15>=s&&d()),B()}catch{i("An error occurred while fetching images.")}});
//# sourceMappingURL=index.js.map
