import{i as y,S as E,a as M}from"./assets/vendor-BDaiwwc1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const b=e=>{const r=document.querySelector(".gallery");if(!Array.isArray(e)||e.length===0){y.error({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topCenter"});return}e.forEach(({webformatURL:s,largeImageURL:t,tags:n,likes:a,views:v,comments:P,downloads:C})=>{const l=document.createElement("div");l.classList.add("gallery-item"),l.innerHTML=`
      <a href="${t}" class="gallery-link">
        <img src="${s}" alt="${n}" class="gallery-image"/>
        <div class="info">
          <p><b>Likes:</b> ${a}</p>
          <p><b>Views:</b> ${v}</p>
          <p><b>Comments:</b> ${P}</p>
          <p><b>Downloads:</b> ${C}</p>
        </div>
      </a>
    `,r.appendChild(l)}),new E(".gallery a").refresh()},g=()=>{const e=document.querySelector(".loader");e?e.style.display="block":console.error("Loading indicator not found.")},m=()=>{const e=document.querySelector(".loader");e?setTimeout(()=>{e.style.display="none"},500):console.error("Loading indicator not found.")},L=()=>{const e=document.querySelector("#load-more-btn");e.style.display="block"},S=()=>{const e=document.querySelector("#load-more-btn");e.style.display="none"},d=()=>{const e=document.querySelector("#load-more-btn");e.style.display="none",y.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"})},$="47394574-2a816324e728e13b0469414a4",I="https://pixabay.com/api/";let h=1;const u=()=>h,q=e=>{h=e},w=async e=>{const r=`${I}?key=${$}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${h}&per_page=15`;try{return g(),(await M.get(r)).data}catch(o){throw console.error(o),o}finally{m()}},B=document.querySelector("#search-form"),f=document.querySelector("#search-input"),H=document.querySelector("#load-more-btn");let c="",p=!0;const i=e=>{y.error({title:"Error",message:e,position:"topCenter"})},T=()=>{const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy(0,e*2)};B.addEventListener("submit",async e=>{if(e.preventDefault(),c=f.value.trim(),c===""){i("Please enter a search term.");return}p||q(1),g();const r=document.querySelector(".gallery");r.innerHTML="";try{const o=await w(c),s=o.hits,t=o.totalHits;s.length===0?(r.innerHTML="",S(),i("There are no images matching your search query. Please try again!")):(b(s),t>u()*15?L():d())}catch{i("An error occurred while fetching images.")}finally{m()}p=!1,f.value=""});H.addEventListener("click",async()=>{const e=u();if(S(),g(),e>=15){d();return}q(e+1);try{const r=await w(c),o=r.hits,s=r.totalHits;o.length===0?i("No more images available."):(b(o),u()*15>=s?d():L()),T()}catch{i("An error occurred while fetching images.")}finally{m()}});
//# sourceMappingURL=index.js.map
